application: localsocialapp
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /register
  script: register.py
  secure: always
  
- url: /message
  script: message.py
  secure: always
  